---
name: "Archlinux MAKEPKG action"
description: "Builds PKGBUILD definition"
author: 'Atom Long'
branding:
  icon: package
  color: blue
inputs:
  arch:
    description: 'CPU architecture: only x86_64 support.'
    required: false
    default: 'x86_64'
  distro:
    description: 'Linux distribution name: archlinux.'
    required: false
    default: 'archlinux'
  githubToken:
    description: 'Your GitHub token, used for caching Docker images in your project''s public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.'
    required: false
    default: ''
  env:
    description: 'Environment variables to propagate to the container. YAML, but must begin with a | character. These variables will be available in both run and setup.'
    required: false
    default: ''
  run:
    description: 'Shell commands to execute in the container.'
    required: false
    default: ''
  shell:
    description: 'The shell to run commands with in the container. Default: /bin/sh on alpine (because Alpine uses BusyBox), /bin/bash for other distros.'
    required: false
    default: ''
  dockerRunArgs:
    description: 'Additional arguments to pass to docker run, such as volume mappings. See README for example usage.'
    required: false
  setup:
    description: 'Shell commands to execute on the host before running the container, such as creating directories for volume mappings. See README for example usage.'
    required: false
    default: ''
  install:
    description: 'Shell commands to execute in the container as part of docker build, such as installing dependencies. This speeds up subsequent builds if githubToken is also used, but note that the image layer will be publicly available in your projects GitHub Package Registry, so make sure the resulting image does not have any secrets cached in logs or state.'
    required: false
    default: ''
  rcloneConfig:
    description: 'rclone configuration file content. Compiled packages will be uploaded to your cloud disk via rclone.'
    required: true
    default: ''
  pgpKey:
    description: 'A private PGP key used to sign the generated package. You can use command "gpg -ao seckey.asc --export-secret-keys <KeyID>" to export your private PGP key.'
    required: true
    default: ''
  pgpKeyPassword:
    description: 'The password of PGP private key.'
    required: true
    default: ''
  deployPath:
    description: 'The path to deploy archlinux package. such as onedrive:mirrors/archlinuxarm/x86_64/core'
    required: true
    default: ''
  pacmanRepo:
    description: 'The repository to which the current archlinux package belongs, such as core,community,extra.'
    required: true
    default: 'aur'
  customRepos:
    description: 'Custom package repositories to install unofficial packages via pacman, such as [aur]http://mirror.archlinuxarm.org/$arch/$repo.'
    required: false
    default: ''
  
runs:
  using: 'node12'
  main: 'src/run-on-arch.js'
