FROM archlinux/base:latest

RUN pacman -Syu --needed --noconfirm \
    binutils \
    fakeroot \
    grep \
    namcap \
    sudo

RUN getent group arch &>/dev/null || groupadd "arch"
RUN getent passwd arch &>/dev/null || useradd -m "arch" -s "/bin/bash" -g "arch"
RUN echo "arch ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN chown -R arch:arch ${CI_BUILD_DIR}

USER arch
